# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-10 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '品牌', 'verbose_name_plural': '品牌'},
        ),
        migrations.AlterModelOptions(
            name='carinfo',
            options={'verbose_name': '汽车信息', 'verbose_name_plural': '汽车信息'},
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
        migrations.AlterModelTable(
            name='carinfo',
            table='carinfo',
        ),
    ]
