# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-10 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartinfo',
            options={'verbose_name': '出价表', 'verbose_name_plural': '出价表'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单表', 'verbose_name_plural': '订单表'},
        ),
        migrations.AlterModelTable(
            name='cartinfo',
            table='cartinfo',
        ),
        migrations.AlterModelTable(
            name='orderinfo',
            table='orderinfo',
        ),
    ]
